spring.application.name=credapp

spring.datasource.url=jdbc:postgresql://localhost:5432/credapp
spring.datasource.username=credapp
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=validate
