credapp.dev.admin-email=dev@credapp.local
credapp.dev.admin-password=${DEV_PASSWORD:devpass}
credapp.dev.admin-group-name=${DEV_GROUP_NAME:}
management.endpoints.web.exposure.include=health,env
spring.docker.compose.lifecycle-management=start-only
server.address=0.0.0.0
server.port=8080
